export const styles = {
  page: {
    width: "100%",
    minHeight: "100vh",
    padding: "20px",
    boxSizing: "border-box",
  },
  title: {
    textAlign: "center",
    marginBottom: 20,
  },
  label: {
    fontWeight: "bold",
  },
  buttonContainer: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
    justifyContent: "center",
    marginBottom: 20,
    alignItems: "center",
  },
  button: {
    padding: "6px 12px",
    borderRadius: 6,
    border: "1px solid #ccc",
    background: "#f0f0f0",
    cursor: "pointer",
  },
  activeButton: {
    background: "#8884d8",
    color: "white",
  },
  cards: {
    display: "flex",
    gap: 15,
    marginBottom: 20,
    flexWrap: "wrap",
  },
  card: {
    border: "1px solid #ddd",
    borderRadius: 10,
    padding: 12,
    background: "#fff",
    color: "#111",
    flex: 1,
    minWidth: 220,
  },
  filters: {
    display: "flex",
    gap: 10,
    marginBottom: 20,
    flexWrap: "wrap",
  },
  chartFilters: {
    display: "flex",
    gap: 15,
    flexWrap: "wrap",
    alignItems: "center",
    marginBottom: 20,
  },
  checkboxLabel: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "#fff",
    color: "#111",
    padding: "6px 10px",
    borderRadius: 6,
    border: "1px solid #ddd",
  },
  input: {
    padding: 8,
    borderRadius: 6,
    border: "1px solid #ccc",
  },
  chartWrapper: {
    width: "100%",
    overflowX: "auto",
    marginBottom: 40,
  },
  subheading: {
    textAlign: "center",
    marginBottom: 20,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(250px, 1fr))",
    gap: 15,
  },
  top10Rank: {
    padding: "10px 16px",
    color: "#bbb",
    fontSize: 12,
    width: 30,
  },
  th: {
    padding: "8px 16px",
    textAlign: "left",
    fontSize: 11,
    color: "#999",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    fontWeight: 500,
  },
};