export const styles = {
  page: {
    width: "100%",
    minHeight: "100vh",
    padding: "12px",
    boxSizing: "border-box",
  },
  title: {
    textAlign: "center",
    marginBottom: 20,
  },
  label: {
    fontWeight: "bold",
  },
  buttonContainer: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    justifyContent: "center",
    marginBottom: 20,
    alignItems: "center",
  },
  button: {
    padding: "8px 14px", 
    borderRadius: 6,
    border: "1px solid #ccc",
    background: "#f0f0f0",
    cursor: "pointer",
    fontSize: 13,
    minHeight: 40, 
  },
  activeButton: {
    background: "#8884d8",
    color: "white",
  },
  cards: {
    display: "flex",
    gap: 12,
    marginBottom: 20,
    flexWrap: "wrap",
  },
  card: {
    border: "1px solid #ddd",
    borderRadius: 10,
    padding: 12,
    background: "#fff",
    color: "#111",
    flex: "1 1 auto",
    minWidth: "160px",
  },
  filters: {
    display: "flex",
    gap: 10,
    marginBottom: 20,
    flexWrap: "wrap",
  },
  chartFilters: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
    alignItems: "center",
    marginBottom: 20,
  },
  checkboxLabel: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "#fff",
    color: "#111",
    padding: "8px 12px", 
    borderRadius: 6,
    border: "1px solid #ddd",
    minHeight: 40, 
  },
  input: {
    padding: 10,
    borderRadius: 6,
    border: "1px solid #ccc",
    fontSize: 14,
    minHeight: 44, 
  },
  chartWrapper: {
    width: "100%",
    overflowX: "auto",
    marginBottom: 40,
    WebkitOverflowScrolling: "touch", 
  },
  subheading: {
    textAlign: "center",
    marginBottom: 20,
    fontSize: "clamp(18px, 5vw, 24px)", 
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))",
    gap: 12,
  },
  top10Rank: {
    padding: "10px 12px",
    color: "#bbb",
    fontSize: 12,
    width: 30,
  },
  th: {
    padding: "8px 12px",
    textAlign: "left",
    fontSize: 11,
    color: "#999",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    fontWeight: 500,
  },
  // mobile-specific responsive breakpoints
  responsiveContainer: {
    overflowX: "auto",
    WebkitOverflowScrolling: "touch",
  },
  tableWrapper: {
    overflowX: "auto",
    WebkitOverflowScrolling: "touch",
    marginBottom: 16,
  },
};